services:
  node:
    image: node
    command: sh -c "npm i && npm start"
    working_dir: /app
    restart: unless-stopped
    volumes:
      - ./:/app
    ports:
      - 3000:3000
      - 3001:3001
